name: pytest CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        make tests

  deploy: # Second job to deploy the application

    runs-on: ubuntu-latest
    needs: build # Ensure this job runs only if the tests pass

    steps:
    - run : echo "Deploying application..."